// Generated by Selenium IDE
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;


public class Demo2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
 //   driver = new ChromeDriver();
//    driver = new FirefoxDriver();
//    js = (JavascriptExecutor) driver;
//    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void conChrome() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    demo2();
  }
  
  @Test
  public void conFirefox() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    demo2();
  }
  
  
  public void demo2() {
    driver.get("http://localhost:8181/");
    driver.manage().window().setSize(new Dimension(1280, 680));
    driver.findElement(By.linkText("Calculadora")).click();
    driver.findElement(By.cssSelector("tr:nth-child(5) > td:nth-child(2) > .btnDigito")).click();
    driver.findElement(By.cssSelector("tr:nth-child(5) > td:nth-child(3) > .btnDigito")).click();
    driver.findElement(By.cssSelector("tr:nth-child(6) .btnOperar")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(3) > .btnDigito")).click();
    driver.findElement(By.cssSelector("tr:nth-child(5) .btnOperar")).click();
    driver.findElement(By.cssSelector("tr:nth-child(7) .btnNum")).click();
    driver.findElement(By.cssSelector("td:nth-child(3) > .btnOperar")).click();
    driver.findElement(By.linkText("Contactos")).click();
    driver.findElements(By.cssSelector(".fas")).get(0).click();
//    driver.findElement(By.cssSelector("tr:nth-child(2) .btn-info > .fas")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) .btn-success")).click();
    driver.findElement(By.id("tratamiento")).click();
    {
      WebElement dropdown = driver.findElement(By.id("tratamiento"));
      dropdown.findElement(By.xpath("//option[. = 'Excmo.']")).click();
    }
    driver.findElement(By.id("tratamiento")).click();
    driver.findElement(By.cssSelector(".form-row:nth-child(1)")).click();
    driver.findElement(By.id("nombre")).sendKeys("d");
    driver.findElement(By.id("apellidos")).click();
    driver.findElement(By.id("btnVolver")).click();
  }
}
